# -*- coding: utf-8 -*-
"""
hato/rank.py -- who is TRIED first, never who is right (RUNBOOK 3b).

🚨 A RANKING CHECK IS RESCUED BY ITS OWN LOWER TIEBREAKS (tsubasa's hot ledger,
bitten twice): a mutant deleting the rule under test survived checks named
after that rule, because a lower key ordered the fixtures correctly anyway.
⭐ So every constructed pair below is built so that the expected winner LOSES
on every key below the one under test -- smaller, older version, a worse fit,
an unseen release, and a name that sorts last -- and each check asserts that
arrangement before it asserts the order.

The real pairs come from aligning the capture of entry 11446 against a stub
folder, so the `[JPN]` / `[CHS, JPN]` sizes are the ones jimaku serves.

What it structurally cannot cover: whether the first candidate is RIGHT. That is
the timing verdict's; ranking only decides the order escalation walks.
"""
import argparse
import json
from pathlib import Path

import pytest
import tsubasa

from hato import episodes, rank, tokens
from hato.commands import rank as rank_command

ROOT = Path(__file__).resolve().parents[1]
API = ROOT / "tests" / "fixtures" / "api"
FILES = json.loads((API / "entries_11446_files.json").read_text(encoding="utf-8"))


def candidate(name, size=30000, quality="range", coverage=1.0, group=None):
    f = {"name": name, "size": size, "last_modified": FILES[0]["last_modified"],
         "url": FILES[0]["url"].rsplit("/", 1)[0] + "/constructed"}
    return episodes.Candidate(f, None, group or tokens.release_group(name), 0, quality, coverage,
                              u"constructed for a ranking check")


def order(ranking):
    return [r.candidate.name for r in ranking.ordered]


def loses_every_lower_key(winner, loser, seen=frozenset()):
    """The arrangement the rescue trap needs, asserted rather than assumed."""
    assert winner.file["size"] < loser.file["size"]
    assert tokens.version(winner.name) <= tokens.version(loser.name)
    assert episodes.QUALITIES.index(winner.quality) >= episodes.QUALITIES.index(loser.quality)
    assert winner.group not in seen
    assert winner.name > loser.name


@pytest.fixture(scope="module")
def episode_three(tmp_path_factory):
    """Every candidate the capture offers one video, aligned for real."""
    root = tmp_path_factory.mktemp("rank")
    folder = root / "v"
    folder.mkdir()
    for n in range(1, 11):
        (folder / (u"[SubsPlease] Sousou no Frieren S2 - %02d (1080p) [ABCD1234].mkv" % n)).write_bytes(b"")
    videos = list(tsubasa.scan(videos=str(folder)).videos)
    a = episodes.align(FILES, videos, workdir=root / "w")
    video = sorted(videos, key=lambda v: v.episode)[2]
    return a.per_video[str(video.path)]


# ---------------------------------------------------------------------------
# the three the RUNBOOK names
# ---------------------------------------------------------------------------

def test_a_chs_jpn_ass_outranks_a_jpn_srt():
    """⭐ RULED 2026-09-17: ".ass above all else. even if it has chinese"."""
    ass = candidate(u"[Zeta] Sousou no Frieren - 31 [WebRip][CHS, JPN].ass", size=20000, quality="literal")
    srt = candidate(u"[Alpha] Sousou no Frieren - 31v2 [WebRip][JPN].srt", size=90000, quality="range")
    assert (tokens.language_class(ass.name), tokens.language_class(srt.name)) == ("multi", "single-ja")
    loses_every_lower_key(ass, srt, seen={srt.group})
    assert order(rank.rank([srt, ass], seen_groups=frozenset([srt.group]))) == [ass.name, srt.name]


def test_within_ass_jpn_outranks_chs_jpn_for_the_same_episode_and_release(episode_three):
    """The capture's own pair: the dual-language file is ~2x the size AND its
    name sorts first -- only the language rule can put `[JPN]` ahead."""
    by_group = {}
    for c in episode_three:
        if c.group == u"Haruhana" and tokens.subtitle_format(c.name) == "ass":
            by_group[tokens.language_class(c.name)] = c
    jpn, chs = by_group["single-ja"], by_group["multi"]
    assert jpn.info.episode == chs.info.episode
    loses_every_lower_key(jpn, chs)
    assert order(rank.rank([chs, jpn])) == [jpn.name, chs.name]


@pytest.mark.parametrize("marker", [u"[whisperai]", u"[Generated by Whisper]"])
def test_an_ai_file_is_excluded_unless_allowed_even_as_ass(marker):
    ai = candidate(u"[Alpha] Sousou no Frieren - 31 [JPN] %s.ass" % marker, size=90000)
    plain = candidate(u"[Zeta] Sousou no Frieren - 31.srt", size=20000, quality="literal")
    assert tokens.is_ai(ai.name) and not tokens.is_ai(plain.name)
    kept = rank.rank([ai, plain])
    assert order(kept) == [plain.name]
    assert [(c.name, u"AI-generated" in why) for c, why in kept.excluded] == [(ai.name, True)]
    allowed = rank.rank([ai, plain], allow_ai=True)
    assert order(allowed) == [ai.name, plain.name] and allowed.excluded == []


# ---------------------------------------------------------------------------
# every other part of the key, each rescue-proof
# ---------------------------------------------------------------------------

def test_ssa_goes_before_srt_and_srt_before_the_rest():
    ssa = candidate(u"[Zeta] Show - 03 [JPN].ssa", size=10000, quality="literal")
    srt = candidate(u"[Mid] Show - 03 [JPN].srt", size=20000, quality="overlap")
    rest = candidate(u"[Alpha] Show - 03 [JPN].vtt", size=90000)
    loses_every_lower_key(ssa, srt)
    loses_every_lower_key(srt, rest)
    assert order(rank.rank([rest, srt, ssa])) == [ssa.name, srt.name, rest.name]


def test_untagged_goes_between_japanese_only_and_dual_language():
    single = candidate(u"[Zeta] Show - 03 [JPN].ass", size=10000, quality="literal")
    untagged = candidate(u"[Mid] Show - 03.ass", size=20000, quality="overlap")
    dual = candidate(u"[Alpha] Show - 03 [CHS, JPN].ass", size=90000)
    loses_every_lower_key(single, untagged)
    loses_every_lower_key(untagged, dual)
    assert order(rank.rank([dual, untagged, single])) == [single.name, untagged.name, dual.name]


def test_a_whole_range_fit_goes_before_a_partial_one_before_a_literal_one():
    whole = candidate(u"[Zeta] Show - 03 [JPN].ass", size=10000, quality="range")
    partial = candidate(u"[Mid] Show - 03 [JPN].ass", size=20000, quality="overlap", coverage=1.0)
    literal = candidate(u"[Alpha] Show - 03 [JPN].ass", size=90000, quality="literal")
    assert order(rank.rank([literal, partial, whole])) == [whole.name, partial.name, literal.name]


def test_a_partial_fit_covering_more_of_its_release_goes_first():
    more = candidate(u"[Zeta] Show - 03 [JPN].ass", size=10000, quality="overlap", coverage=1.0)
    less = candidate(u"[Alpha] Show - 03 [JPN].ass", size=90000, quality="overlap", coverage=0.5)
    loses_every_lower_key(more, less)
    assert order(rank.rank([less, more])) == [more.name, less.name]


def test_a_literal_match_is_not_ranked_by_the_size_of_its_release():
    """Against one video every release lands one episode, so coverage is
    1/(release size): ranking by it would try a SHORT release first."""
    complete = candidate(u"[Zeta] Show - 03 [JPN].ass", size=90000, quality="literal", coverage=0.1)
    short = candidate(u"[Alpha] Show - 03 [JPN].ass", size=10000, quality="literal", coverage=0.5)
    assert order(rank.rank([short, complete])) == [complete.name, short.name]


def test_a_higher_release_version_goes_first():
    v2 = candidate(u"[Zeta] Show - 03v2 [JPN].ass", size=10000)
    v1 = candidate(u"[Alpha] Show - 03 [JPN].ass", size=90000)
    assert v2.name > v1.name and v2.file["size"] < v1.file["size"]
    assert order(rank.rank([v1, v2])) == [v2.name, v1.name]


def test_bigger_goes_first_within_one_format_and_language_class():
    big = candidate(u"[Zeta] Show - 03 [JPN].ass", size=90000)
    small = candidate(u"[Alpha] Show - 03 [JPN].ass", size=10000)
    assert order(rank.rank([small, big], seen_groups=frozenset([small.group]))) == [big.name, small.name]


def test_a_release_already_seen_to_succeed_goes_first_on_a_tie():
    seen = candidate(u"[Zeta] Show - 03 [JPN].ass", size=30000)
    unseen = candidate(u"[Alpha] Show - 03 [JPN].ass", size=30000)
    assert order(rank.rank([unseen, seen], seen_groups=frozenset([seen.group]))) == [seen.name, unseen.name]


def test_size_is_never_compared_across_a_format_or_a_language_class(episode_three):
    """⚠ The rule, not a pair: turn every size upside down and no candidate may
    cross a format or a language-class boundary -- only order inside one moves."""
    def buckets(cands):
        return [(tokens.subtitle_format(r.candidate.name), tokens.language_class(r.candidate.name))
                for r in rank.rank(cands).ordered]

    sizes = [c.file["size"] for c in episode_three]
    flipped = []
    for c in episode_three:
        f = dict(c.file, size=max(sizes) + min(sizes) - c.file["size"])
        flipped.append(episodes.Candidate(f, c.info, c.group, c.offset, c.quality, c.coverage, c.reason))
    before, after = buckets(episode_three), buckets(flipped)
    assert len(set(before)) > 2, before
    assert after == before
    assert order(rank.rank(flipped)) != order(rank.rank(episode_three)), "size still orders inside a bucket"


def test_two_formats_outside_the_ruled_order_are_never_separated_by_size():
    """🚨 SIZE *WAS* COMPARED ACROSS FORMATS. `.ass`, `.ssa` and `.srt` are
    ranked; everything else shared ONE rank -- so a `.vtt` and a `.sup` tied on
    part 1, fell through to part 7 and were ordered by SIZE, while the printed
    reason said *"size is only ever compared between .vtt Japanese-only files"*.
    The invariant of key part 7 was simply false.

    ⚠ THE CAPTURE HOLDS ONLY `.ass` AND `.srt`, so the rule-shaped check above
    -- which flips every size on the real capture -- structurally cannot see it.
    The format is what varies here.
    """
    big = candidate(u"[Alpha] Show - 03 [JPN].sup", size=90000)
    small = candidate(u"[Zeta] Show - 03 [JPN].vtt", size=10000)
    assert {tokens.subtitle_format(c.name) for c in (big, small)} == {"sup", "vtt"}
    assert not {tokens.subtitle_format(c.name) for c in (big, small)} & set(rank.FORMAT_ORDER)
    # the rescue trap: the loser wins every key below the one under test
    assert big.file["size"] > small.file["size"] and big.name < small.name

    ranking = rank.rank([small, big])
    assert order(ranking) == [big.name, small.name]         # .sup < .vtt, by extension
    why = u" ".join(ranking.ordered[0].reasons)
    assert u"the extension decides" in why and u"Never their size" in why, why
    # and the sizes are what would have decided it the other way
    flipped = candidate(u"[Alpha] Show - 03 [JPN].sup", size=10000)
    assert order(rank.rank([small, flipped])) == [flipped.name, small.name]


def test_an_unbroken_tie_guess_is_tried_after_a_literal_number():
    """⭐ `guess` sits BELOW `literal`. An anchored placement is a coin flip
    between the members of a tie; a literal number is what both sides wrote
    down. Ranked as an `overlap` -- which is what it used to be -- a
    wrong-episode guess took #1 from a correctly-placed release."""
    guess = candidate(u"[Alpha] Show - 03 [JPN].ass", size=90000, quality="guess", coverage=1.0)
    literal = candidate(u"[Zeta] Show - 03 [JPN].ass", size=10000, quality="literal", coverage=0.1)
    assert episodes.QUALITIES.index("guess") > episodes.QUALITIES.index("literal")
    assert guess.file["size"] > literal.file["size"] and guess.name < literal.name
    ranking = rank.rank([guess, literal])
    assert order(ranking) == [literal.name, guess.name]
    # ⚠ AMENDED 2026-09-17: the sentence moved UP a key part and got stronger. A
    # guess used to lose to a literal number on `fit`, which sits BELOW format --
    # so an `.ass` guess still beat an `.srt` literal number (measured live, and it
    # took #1 from files whose own number read 3). Now it loses on `known`, which
    # sits above format. ⭐ The behaviour asserted above is unchanged; what changed
    # is that it now holds whatever format either file is in.
    said = u" ".join(ranking.ordered[0].reasons)
    assert u"known, not guessed" in said and u"whatever format" in said, said


def test_the_offset_both_sides_already_name_breaks_a_tie_between_equal_fits():
    """⭐ A NEW KEY PART, and nothing used this evidence. Two candidates that
    tie on format, language, fit and coverage used to fall straight to size and
    the name -- so a release re-numbered by +28 could take #1 from one whose
    file and video agree on the episode. The agreeing one goes first."""
    agreed = candidate(u"[Zeta] Show - 03 [JPN].ass", size=10000)
    shifted = candidate(u"[Alpha] Show - 03 [JPN].ass", size=90000)
    shifted = episodes.Candidate(shifted.file, None, shifted.group, 28, "range", 1.0, u"shifted")
    assert agreed.offset == 0 and shifted.offset == 28
    assert agreed.quality == shifted.quality and agreed.coverage == shifted.coverage
    # the rescue trap: the winner loses size AND the name
    assert agreed.file["size"] < shifted.file["size"] and agreed.name > shifted.name
    ranking = rank.rank([shifted, agreed])
    assert order(ranking) == [agreed.name, shifted.name]
    assert u"both sides already name" in u" ".join(ranking.ordered[0].reasons)


# ---------------------------------------------------------------------------
# filters, completeness, determinism
# ---------------------------------------------------------------------------

def test_a_file_tagged_only_non_japanese_is_filtered_not_ranked():
    """Ruling 5. The corpus's only such name, as an .ass that would go first."""
    chinese = candidate(u"[WYQsub]Kizumonogatari Reiketsu Hen[GB][BDRip][1080P].ass", size=90000)
    japanese = candidate(u"[Zeta] Kizumonogatari Reiketsu Hen.srt", size=10000, quality="literal")
    ranking = rank.rank([chinese, japanese])
    assert order(ranking) == [japanese.name]
    assert [(c.name, u"Chinese" in why) for c, why in ranking.excluded] == [(chinese.name, True)]


def test_a_duplicate_is_tried_once():
    one = candidate(u"[Alpha] Show - 03 [JPN].ass")
    ranking = rank.rank([one, one])
    assert order(ranking) == [one.name] and len(ranking.excluded) == 1


def test_ranking_never_drops_a_candidate_it_does_not_name(episode_three):
    extra = [candidate(u"[WhisperAI] Show - 03.ass"), episode_three[0]]
    ranking = rank.rank(list(episode_three) + extra)
    assert len(ranking.ordered) + len(ranking.excluded) == len(episode_three) + len(extra)
    assert all(why for _c, why in ranking.excluded)


def test_the_order_never_depends_on_the_input_order(episode_three):
    forward = order(rank.rank(list(episode_three)))
    assert order(rank.rank(list(reversed(episode_three)))) == forward
    assert len(forward) == len({c.name for c in episode_three})
    # ⚠ the capture never ties on every key, so a true tie is built: only the name is left
    a = candidate(u"[Alpha] Show - 03 [JPN].ass", size=30000)
    b = candidate(u"[Beta] Show - 03 [JPN].ass", size=30000)
    assert order(rank.rank([b, a])) == order(rank.rank([a, b])) == [a.name, b.name]


# ---------------------------------------------------------------------------
# the reasons, the rendering, the command
# ---------------------------------------------------------------------------

def test_every_candidate_carries_the_reason_for_its_place(episode_three):
    ranking = rank.rank(episode_three)
    for i, r in enumerate(ranking.ordered):
        above = [s for s in r.reasons if s.startswith(u"Above #%d:" % (i + 2))]
        below = [s for s in r.reasons if s.startswith(u"Below #%d:" % i)]
        assert len(above) == (1 if i + 1 < len(ranking.ordered) else 0), r.reasons
        assert len(below) == (1 if i else 0), r.reasons
    names = [tokens.subtitle_format(r.candidate.name) for r in ranking.ordered]
    boundary = names.index("srt")
    assert u".ass is tried before .srt" in ranking.ordered[boundary].reasons[0]


def test_explain_prints_every_candidate_with_its_key_and_reasons_and_every_exclusion(episode_three):
    ai = candidate(u"[WhisperAI] Sousou no Frieren - 31.ass")
    ranking = rank.rank(list(episode_three) + [ai])
    text = rank.explain(ranking)
    lines = text.splitlines()
    for i, r in enumerate(ranking.ordered):
        row = [l for l in lines if l.endswith(r.candidate.name) and l.split()[0] == str(i + 1)]
        assert len(row) == 1, r.candidate.name
        assert u"{:,}".format(r.candidate.file["size"]) in row[0]
        assert all(reason in text for reason in r.reasons)
    assert u"EXCLUDED" in text and ai.name in text.split(u"EXCLUDED", 1)[1]


def _run_rank(argv):
    parser = argparse.ArgumentParser(prog="hato rank")
    rank_command.register(parser)
    return rank_command.run(parser.parse_args(argv))


def test_hato_rank_without_a_recorded_list_says_the_live_path_waits_for_2c(capsys):
    assert _run_rank(["--explain", "11446", "3"]) == 2
    err = capsys.readouterr().err
    assert u"RUNBOOK 2c" in err and len(err.strip().splitlines()) == 1


def test_hato_rank_with_no_folder_ranks_the_files_whose_own_number_matches(tmp_path, capsys, episode_three):
    assert _run_rank(["--explain", "11446", "3", "--files", str(API / "entries_11446_files.json")]) == 0
    out = capsys.readouterr().out
    literal = [f["name"] for f in FILES
               if any(c.name == f["name"] and c.info.episode == 3 for c in episode_three)]
    assert literal and all(n in out for n in literal)
    assert u"soft spot" in out
    # ⚠ AMENDED 2026-09-17: this asserted that NO file whose own number differs is
    # shown. A lone video is now also offered each release's file at its POSITION
    # (`episodes.py::_offer_by_position`) -- the whole point being that refusing to
    # offer anything left the commonest shape with no subtitle at all. What must
    # still hold is the ORDER and the LABEL: the literal numbers rank first, and
    # anything else is shown as the guess it is.
    lines = [line for line in out.splitlines() if line.strip()]
    first_literal = min(i for i, line in enumerate(lines) if any(n in line for n in literal))
    others = [i for i, line in enumerate(lines)
              if any(c.name in line for c in episode_three if c.info.episode != 3)]
    assert all(i > first_literal for i in others), out
    assert not others or u"position" in out or u"guess" in out, out


@pytest.mark.parametrize("allow", [False, True])
def test_hato_rank_passes_allow_ai_through(tmp_path, capsys, allow):
    """A recorded list with one AI `.ass` added (constructed; written to tmp_path,
    never beside the real capture)."""
    ai_name = u"[WhisperAI] Sousou no Frieren S2 - 03 [JPN].ass"
    listed = tmp_path / "with_ai.json"
    listed.write_text(json.dumps(FILES + [dict(FILES[0], name=ai_name)], ensure_ascii=False), encoding="utf-8")
    argv = ["--explain", "11446", "3", "--files", str(listed)] + (["--allow-ai"] if allow else [])
    assert _run_rank(argv) == 0
    out = capsys.readouterr().out
    ranked, _, excluded = out.partition(u"EXCLUDED")
    assert (ai_name in ranked) == allow and (ai_name in excluded) == (not allow), out


def test_hato_rank_with_a_folder_prints_exactly_the_ranking_of_that_video(tmp_path, capsys, episode_three):
    folder = tmp_path / "v"
    folder.mkdir()
    for n in range(1, 11):
        (folder / (u"[SubsPlease] Sousou no Frieren S2 - %02d (1080p) [ABCD1234].mkv" % n)).write_bytes(b"")
    assert _run_rank(["--explain", "11446", "3", "--files", str(API / "entries_11446_files.json"),
                      "--folder", str(folder)]) == 0
    out = capsys.readouterr().out
    assert rank.explain(rank.rank(episode_three)) in out
